
[data_dir]
site = "data/site"
env_constraints = "data/env_constraints"
targets = "data/targets"
target_scenarios = "data/targets/scenarios"


[output_dir]
path = "outputs"

[parameters]
EPSG_code = 7844

depot_x = 50.0
depot_y = 200.0

suitable_threshold = 50.0
k = 5
cluster_tolerance = 1.0

depth_ms = -10.0
depth_t = -5.0

weight_ms = 1.0
weight_t = 1.0

n_tenders = 3
t_cap = 2
